# Generated by Django 4.1.5 on 2023-01-31 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32, verbose_name='Contraseña')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45, verbose_name='Primer nombre')),
                ('second_name', models.CharField(blank=True, max_length=45, null=True, verbose_name='Segundo nombre')),
                ('last_name', models.CharField(max_length=45, verbose_name='Primer apellido')),
                ('second_last_name', models.CharField(blank=True, max_length=45, null=True, verbose_name='Segundo apellido')),
                ('doc_type', models.CharField(choices=[('1', 'Cédula'), ('2', 'Pasaporte')], max_length=1, verbose_name='Tipo Documento')),
                ('doc_number', models.PositiveIntegerField(verbose_name='Numero documento')),
                ('telephone_number', models.IntegerField(verbose_name='Teléfono')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserDetails', to='api_users.user')),
            ],
            options={
                'verbose_name': 'Detalles de usuario',
                'verbose_name_plural': 'Detalles de usuarios',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion. Primera línea')),
                ('address_line2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección. Segunda línea')),
                ('city', models.CharField(blank=True, max_length=45, null=True, verbose_name='Ciudad')),
                ('district', models.CharField(blank=True, max_length=45, null=True, verbose_name='Municipio')),
                ('country', models.CharField(blank=True, max_length=45, null=True, verbose_name='País')),
                ('userDetails', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Dirección', to='api_users.userdetails')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'ordering': ['country', 'city', 'district', 'address_line1'],
            },
        ),
    ]
