# Generated by Django 4.1.5 on 2023-01-31 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='userDetails',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='UserDetails', to='api_users.address'),
        ),
    ]
