# Generated by Django 4.1.5 on 2023-02-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0002_remove_address_userdetails_userdetails_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['region', 'province', 'city', 'address_line1'], 'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='district',
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Región'),
        ),
    ]
