# Generated by Django 4.1.5 on 2023-01-31 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, null=True, verbose_name='Código')),
                ('name', models.CharField(max_length=45, null=True, verbose_name='Nombre')),
                ('description', models.TextField(null=True, verbose_name='Descripción')),
                ('price', models.FloatField(null=True, verbose_name='Precio')),
                ('cost', models.FloatField(null=True, verbose_name='Costo')),
                ('stock', models.PositiveBigIntegerField(null=True, verbose_name='Stock')),
                ('image', models.ImageField(upload_to='Media/Productos', verbose_name='Imagen')),
                ('category', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Productos', to='api_inventary.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
    ]
